import type { WalletState } from "./types";

export const DEFAULT_STATE: WalletState = {
  walletName: "Account 1",
  address: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
  tokens: [
    {
      id: "sol",
      symbol: "SOL",
      name: "Solana",
      amount: 1284.52,
      coingeckoId: "solana",
      priceUsd: 178.4,
      change24h: 2.14,
      color: "#9945FF",
    },
    {
      id: "usdc",
      symbol: "USDC",
      name: "USD Coin",
      amount: 48210.11,
      coingeckoId: "usd-coin",
      priceUsd: 1,
      change24h: 0.01,
      color: "#2775CA",
    },
    {
      id: "jup",
      symbol: "JUP",
      name: "Jupiter",
      amount: 84200,
      coingeckoId: "jupiter-exchange-solana",
      priceUsd: 0.62,
      change24h: -1.8,
      color: "#16C784",
    },
    {
      id: "bonk",
      symbol: "BONK",
      name: "Bonk",
      amount: 240_000_000,
      coingeckoId: "bonk",
      priceUsd: 0.000021,
      change24h: 6.4,
      color: "#F5A623",
    },
    {
      id: "wif",
      symbol: "WIF",
      name: "dogwifhat",
      amount: 3200,
      coingeckoId: "dogwifcoin",
      priceUsd: 1.84,
      change24h: -3.2,
      color: "#E8A87C",
    },
  ],
  collectibles: [
    { id: "nft-1", name: "#4421", collection: "Mad Lads", color: "#7C5CFF" },
    { id: "nft-2", name: "#881", collection: "Tensorians", color: "#22D3EE" },
    { id: "nft-3", name: "#1204", collection: "Claynosaurz", color: "#F472B6" },
    { id: "nft-4", name: "#77", collection: "SMB Gen2", color: "#FBBF24" },
  ],
  activity: [
    {
      id: "a1",
      kind: "receive",
      title: "Received SOL",
      subtitle: "From 9xK1...pQ2a",
      amountLabel: "+12.40 SOL",
      usdLabel: "+$2,212.16",
      at: "Today, 2:14 PM",
    },
    {
      id: "a2",
      kind: "swap",
      title: "Swapped USDC → JUP",
      subtitle: "Jupiter",
      amountLabel: "2,500 USDC",
      usdLabel: "$2,500.00",
      at: "Yesterday, 8:03 PM",
    },
    {
      id: "a3",
      kind: "send",
      title: "Sent SOL",
      subtitle: "To 4nR8...kLm2",
      amountLabel: "-4.00 SOL",
      usdLabel: "-$713.60",
      at: "Aug 21, 11:40 AM",
    },
  ],
};
