import type { Token, WalletState } from "./types";

export const CATALOG: Token[] = [
  {
    id: "btc",
    symbol: "BTC",
    name: "Bitcoin",
    amount: 2.2841,
    coingeckoId: "bitcoin",
    binanceSymbol: "BTCUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#F7931A",
    verified: true,
  },
  {
    id: "eth",
    symbol: "ETH",
    name: "Ethereum",
    amount: 42.118,
    coingeckoId: "ethereum",
    binanceSymbol: "ETHUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#627EEA",
    verified: true,
  },
  {
    id: "sol",
    symbol: "SOL",
    name: "Solana",
    amount: 318.4,
    coingeckoId: "solana",
    binanceSymbol: "SOLUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#9945FF",
    verified: true,
  },
  {
    id: "bnb",
    symbol: "BNB",
    name: "BNB",
    amount: 88.2,
    coingeckoId: "binancecoin",
    binanceSymbol: "BNBUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#F3BA2F",
    verified: true,
  },
  {
    id: "xrp",
    symbol: "XRP",
    name: "XRP",
    amount: 42000,
    coingeckoId: "ripple",
    binanceSymbol: "XRPUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#23292F",
    verified: true,
  },
  {
    id: "ada",
    symbol: "ADA",
    name: "Cardano",
    amount: 25000,
    coingeckoId: "cardano",
    binanceSymbol: "ADAUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#0033AD",
    verified: true,
  },
  {
    id: "doge",
    symbol: "DOGE",
    name: "Dogecoin",
    amount: 180000,
    coingeckoId: "dogecoin",
    binanceSymbol: "DOGEUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#C2A633",
    verified: true,
  },
  {
    id: "avax",
    symbol: "AVAX",
    name: "Avalanche",
    amount: 640,
    coingeckoId: "avalanche-2",
    binanceSymbol: "AVAXUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#E84142",
    verified: true,
  },
  {
    id: "link",
    symbol: "LINK",
    name: "Chainlink",
    amount: 2100,
    coingeckoId: "chainlink",
    binanceSymbol: "LINKUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#2A5ADA",
    verified: true,
  },
  {
    id: "sui",
    symbol: "SUI",
    name: "Sui",
    amount: 8900,
    coingeckoId: "sui",
    binanceSymbol: "SUIUSDT",
    priceUsd: 0,
    change24h: 0,
    sparkline: [],
    color: "#4DA2FF",
    verified: true,
  },
  {
    id: "usdc",
    symbol: "USDC",
    name: "USD Coin",
    amount: 28410.5,
    coingeckoId: "usd-coin",
    binanceSymbol: "USDCUSDT",
    priceUsd: 1,
    change24h: 0,
    sparkline: [],
    color: "#2775CA",
    verified: true,
  },
  {
    id: "usdt",
    symbol: "USDT",
    name: "Tether",
    amount: 12100,
    coingeckoId: "tether",
    priceUsd: 1,
    change24h: 0,
    sparkline: [],
    color: "#26A17B",
    verified: true,
  },
];

export const DEFAULT_STATE: WalletState = {
  walletName: "Main Wallet",
  address: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
  cashUsd: 8420.15,
  layout: "phantom",
  tokens: CATALOG,
  collectibles: [
    { id: "nft-1", name: "#4421", collection: "Mad Lads", color: "#7C5CFF" },
    { id: "nft-2", name: "#881", collection: "Tensorians", color: "#22D3EE" },
    { id: "nft-3", name: "#1204", collection: "Claynosaurz", color: "#F472B6" },
    { id: "nft-4", name: "#77", collection: "SMB Gen2", color: "#FBBF24" },
  ],
  activity: [
    {
      id: "a1",
      kind: "receive",
      title: "Received SOL",
      subtitle: "Simulated",
      amountLabel: "+12.40 SOL",
      usdLabel: "—",
      at: "Today, 2:14 PM",
    },
    {
      id: "a2",
      kind: "swap",
      title: "Swapped USDC → ETH",
      subtitle: "Simulated",
      amountLabel: "2,500 USDC",
      usdLabel: "—",
      at: "Yesterday, 8:03 PM",
    },
  ],
};
