import type { WalletState } from "./types";

export const DEFAULT_STATE: WalletState = {
  walletName: "Larpz Wallet",
  address: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
  cashUsd: 52333.83,
  layout: "larpz",
  tokens: [
    {
      id: "eth",
      symbol: "ETH",
      name: "Ethereum",
      amount: 433.623,
      coingeckoId: "ethereum",
      priceUsd: 1643.0,
      change24h: -2.49,
      color: "#627EEA",
      verified: true,
    },
    {
      id: "btc",
      symbol: "BTC",
      name: "Bitcoin",
      amount: 2.28,
      coingeckoId: "bitcoin",
      priceUsd: 108454,
      change24h: -1.92,
      color: "#F7931A",
      verified: true,
    },
    {
      id: "sol",
      symbol: "SOL",
      name: "Solana",
      amount: 1684.2,
      coingeckoId: "solana",
      priceUsd: 140.72,
      change24h: -2.31,
      color: "#9945FF",
      verified: true,
    },
    {
      id: "usdc",
      symbol: "USDC",
      name: "USDC",
      amount: 61583.63,
      coingeckoId: "usd-coin",
      priceUsd: 1,
      change24h: 0.02,
      color: "#2775CA",
      verified: true,
    },
    {
      id: "wcc",
      symbol: "WCC",
      name: "World Cup Coin",
      amount: 84200,
      coingeckoId: "",
      priceUsd: 0.6,
      change24h: -18.02,
      color: "#3B82F6",
      verified: false,
    },
    {
      id: "mon",
      symbol: "MON",
      name: "Monad",
      amount: 0,
      coingeckoId: "",
      priceUsd: 0,
      change24h: 0,
      color: "#836EF9",
      verified: true,
    },
  ],
  collectibles: [
    { id: "nft-1", name: "#4421", collection: "Mad Lads", color: "#7C5CFF" },
    { id: "nft-2", name: "#881", collection: "Tensorians", color: "#22D3EE" },
    { id: "nft-3", name: "#1204", collection: "Claynosaurz", color: "#F472B6" },
    { id: "nft-4", name: "#77", collection: "SMB Gen2", color: "#FBBF24" },
  ],
  activity: [
    {
      id: "a1",
      kind: "receive",
      title: "Received SOL",
      subtitle: "From 9xK1...pQ2a",
      amountLabel: "+12.40 SOL",
      usdLabel: "+$2,212.16",
      at: "Today, 2:14 PM",
    },
    {
      id: "a2",
      kind: "swap",
      title: "Swapped USDC → ETH",
      subtitle: "Simulator",
      amountLabel: "2,500 USDC",
      usdLabel: "$2,500.00",
      at: "Yesterday, 8:03 PM",
    },
    {
      id: "a3",
      kind: "send",
      title: "Sent SOL",
      subtitle: "To 4nR8...kLm2",
      amountLabel: "-4.00 SOL",
      usdLabel: "-$562.88",
      at: "Aug 21, 11:40 AM",
    },
  ],
};
